services:
  HeimrichHannot\FormgeneratorTypeBundle\:
    resource: '../src/{Controller,EventListener}/*'
    autoconfigure: true
    autowire: true

  HeimrichHannot\FormgeneratorTypeBundle\FormgeneratorType\FormgeneratorTypeCollection:
    autowire: true