services:
  HeimrichHannot\FormTypeBundle\:
    resource: '../src/{Controller,EventListener}/*'
    autoconfigure: true
    autowire: true

  HeimrichHannot\FormTypeBundle\FormType\FormTypeCollection:
    autowire: true